export const REGISTER_BID = 'REGISTER_BID';

export const GET_BID_LIST_DESIGNER = 'GET_BID_LIST_DESIGNER';
export const GET_BID_LIST_DESIGNER_SUCCESS = 'GET_BID_LIST_DESIGNER_SUCCESS';
export const GET_BID_LIST_DESIGNER_ERROR = 'GET_BID_LIST_DESIGNER_ERROR';
