export const GET_MATCHING_LIST_DESIGNER = 'GET_MATCHING_LIST_DESIGNER';
export const GET_MATCHING_LIST_DESIGNER_SUCCESS = 'GET_MATCHING_LIST_DESIGNER_SUCCESS';
export const GET_MATCHING_LIST_DESIGNER_ERROR = 'GET_MATCHING_LIST_DESIGNER_ERROR';
