export const REGISTER_MATCHING = 'REGISTER_MATCHING';
export const PATCH_MATCHING = 'PATCH_MATCHING';
export const DELETE_MATCHING = 'DELETE_MATCHING';

export const GET_MATCHING_LIST_DESIGNER = 'GET_MATCHING_LIST_DESIGNER';
export const GET_MATCHING_LIST_DESIGNER_SUCCESS = 'GET_MATCHING_LIST_DESIGNER_SUCCESS';
export const GET_MATCHING_LIST_DESIGNER_ERROR = 'GET_MATCHING_LIST_DESIGNER_ERROR';

export const GET_MATCHING_LIST_CUSTOMER = 'GET_MATCHING_LIST_CUSTOMER';
export const GET_MATCHING_LIST_CUSTOMER_SUCCESS = 'GET_MATCHING_LIST_CUSTOMER_SUCCESS';
export const GET_MATCHING_LIST_CUSTOMER_ERROR = 'GET_MATCHING_LIST_CUSTOMER_ERROR';

export const GET_MATCHINGHISTORY_LIST_DESIGNER = 'GET_MATCHINGHISTORY_LIST_DESIGNER';
export const GET_MATCHINGHISTORY_LIST_DESIGNER_SUCCESS =
  'GET_MATCHINGHISTORY_LIST_DESIGNER_SUCCESS';
export const GET_MATCHINGHISTORY_LIST_DESIGNER_ERROR = 'GET_MATCHINGHISTORY_LIST_DESIGNER_ERROR';

export const GET_MATCHINGHISTORY_LIST_CUSTOMER = 'GET_MATCHINGHISTORY_LIST_CUSTOMER';
export const GET_MATCHINGHISTORY_LIST_CUSTOMER_SUCCESS =
  'GET_MATCHINGHISTORY_LIST_CUSTOMER_SUCCESS';
export const GET_MATCHINGHISTORY_LIST_CUSTOMER_ERROR = 'GET_MATCHINGHISTORY_LIST_CUSTOMER_ERROR';
