export const GET_BRANDING_LIST_DESIGNER = 'GET_BRANDING_LIST_DESIGNER';
export const GET_BRANDING_LIST_DESIGNER_SUCCESS = 'GET_BRANDING_LIST_DESIGNER_SUCCESS';
export const GET_BRANDING_LIST_DESIGNER_ERROR = 'GET_BRANDING_LIST_DESIGNER_ERROR';
