export const REGISTER_BRANDING = 'REGISTER_BRANDING';
export const PATCH_BRANDING = 'PATCH_BRANDING';
export const DELETE_BRANDING = 'DELETE_BRANDING';

export const GET_BRANDING_LIST = 'GET_BRANDING_LIST';
export const GET_BRANDING_LIST_SUCCESS = 'GET_BRANDING_LIST_SUCCESS';
export const GET_BRANDING_LIST_ERROR = 'GET_BRANDING_LIST_ERROR';
