export const GET_STYLE_LIST = 'GET_STYLE_LIST';
export const GET_STYLE_LIST_SUCCESS = 'GET_STYLE_LIST_SUCCESS';
export const GET_STYLE_LIST_ERROR = 'GET_STYLE_LIST_ERROR';

export const PATCH_STYLE = 'PATCH_STYLE';
export const DELETE_STYLE = 'DELETE_STYLE';
