export const REGISTER_SCHEDULEINFO = 'REGISTER_SCHEDULEINFO';
export const REGISTER_SCHEDULEINFO_SUCCESS = 'REGISTER_SCHEDULEINFO_SUCCESS';
export const REGISTER_SCHEDULEINFO_ERROR = 'REGISTER_SCHEDULEINFO_ERROR';
export const GET_SCHEDULEINFO = 'GET_SCHEDULEINFO';
export const GET_SCHEDULEINFO_SUCCESS = 'GET_SCHEDULEINFO_SUCCESS';
export const GET_SCHEDULEINFO_ERROR = 'GET_SCHEDULEINFO_ERROR';
export const PATCH_SCHEDULEINFO = 'PATCH_SCHEDULEINFO';
export const DELETE_SCHEDULEINFO = 'DELETE_SCHEDULEINFO';
